### ISSUE TITLE
[Feature Request] Satoshi denominated tpos

### ISSUE THREAD

**Issue by iWarpBTC** [lnbits/tpos#58]
Isn't it time that tpos could be denominated directly in satoshis? 

Now I'm forced to choose a currency from a plethora of fiat shitcoins.

**Comment by prusnak** [comment]
I tried to come up with a PR, but there are so many places that need refactoring because the current code assumes there always be an exchange rate and we always need to show two different amounts.

Refactoring shouldn't be that hard, but also it is not a 5 minute job, I initially thought it would be.

**Comment by prusnak** [comment]
Done in https://github.com/lnbits/tpos/pull/63
